# 2025-08-02 자력 해결
# CATEGORY를 내림차순으로 쓰라 했는데 애먼 칼럼을 넣어놓고 왜 안 되냐고 헤매고 있었다

WITH CALC AS (
    SELECT B.BOOK_ID, AUTHOR_ID, CATEGORY, PRICE, SALES, SALES_DATE
    FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
)

SELECT
    A.AUTHOR_ID, AUTHOR_NAME, CATEGORY,
    SUM(PRICE * SALES) AS TOTAL_SALES
FROM CALC C JOIN AUTHOR A ON C.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC ;
