SELECT C.ID FROM ECOLI_DATA A
INNER JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
INNER JOIN ECOLI_DATA C ON B.ID = C.PARENT_ID
WHERE C.ID NOT IN (
SELECT G.ID FROM ECOLI_DATA D
INNER JOIN ECOLI_DATA E ON D.ID = E.PARENT_ID
INNER JOIN ECOLI_DATA F ON E.ID = F.PARENT_ID
INNER JOIN ECOLI_DATA G ON F.ID = G.PARENT_ID
)