SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID IN (SELECT P.ITEM_ID
FROM ITEM_TREE P LEFT JOIN ITEM_TREE C ON P.ITEM_ID = C.PARENT_ITEM_ID
WHERE C.ITEM_ID IS NULL)
ORDER BY ITEM_ID DESC ;





