# SELECT I.ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO I
# WHERE I.ITEM_ID NOT IN
#     (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
# ORDER BY I.ITEM_ID DESC;


SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I 
WHERE NOT EXISTS (SELECT 1 FROM ITEM_TREE T WHERE I.ITEM_ID=T.PARENT_ITEM_ID)
ORDER BY I.ITEM_ID DESC ;    