# SELECT I.ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO I
# WHERE I.ITEM_ID NOT IN
#     (SELECT PARENT_ITEM_ID FROM ITEM_TREE)
  # 이렇게 쓰면 PARENT_ITEM_ID에 NULL이 있을 때 IN이 TRUE인지 FALSE인지 구별하지 못하고 UNKNOWN으로 결론을 내려버려 비교가 불가능하다
  # 이 방법으로 쓰려면 서브쿼리에 반드시 WHERE PARENT_ITEM_ID IS NOT NULL까지 써야 한다!)
# ORDER BY I.ITEM_ID DESC;



SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I 
WHERE NOT EXISTS (SELECT 1 FROM ITEM_TREE T WHERE I.ITEM_ID=T.PARENT_ITEM_ID)
ORDER BY I.ITEM_ID DESC ;    
