# 2025-07-25 16:10에 푼 문제
# 부모-자식 관계 쿼리문으로 LEFT JOIN과 ON을 잘 활용했음
SELECT P.ID, COUNT(C.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA AS P LEFT JOIN ECOLI_DATA AS C ON P.ID = C.PARENT_ID
GROUP BY P.ID
ORDER BY P.ID






