-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# GROUP BY USER_ID, PRODUCT_ID
# HAVING COUNT(*) >= 2
# ORDER BY USER_ID, PRODUCT_ID DESC ;


SELECT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE AS A JOIN ONLINE_SALE AS B
WHERE A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID
AND A.SALES_DATE != B.SALES_DATE
GROUP BY A.USER_ID, A.PRODUCT_ID
ORDER BY USER_ID, PRODUCT_ID DESC ;




