# 2025-07-31 자력 해결
# 열 수가 맞지 않는 문제를 바로 NULL을 투입해 해결
# UNION으로 양 테이블을 이으면 칼럼명은 첫 테이블을 따르기 때문에 둘째 테이블은 이름을 바꿀 필요가 없다~

SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        N.PRODUCT_ID, USER_ID, N.SALES_AMOUNT
FROM ONLINE_SALE AS N
WHERE N.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION

SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d'),
        F.PRODUCT_ID, NULL, F.SALES_AMOUNT
FROM OFFLINE_SALE AS F
WHERE F.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY 1, 2, 3

#==================================================================================

# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
#        PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

# UNION ALL

# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
#        PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;







