-- 코드를 입력하세요
# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
#        PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

# UNION ALL

# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
#        PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;



SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        N.PRODUCT_ID, USER_ID, N.SALES_AMOUNT
FROM ONLINE_SALE AS N
WHERE N.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION

SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d'),
        F.PRODUCT_ID, NULL, F.SALES_AMOUNT
FROM OFFLINE_SALE AS F
WHERE F.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY 1, 2, 3



