# 2025-07-28 못 푼 문제
# ON 절에도 바로 AND OR을 쓸 수가 있다는 점
# 고난도 문제일수록 서브쿼리와 IN 연산자가 많이 쓰이는 것을 확인

SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 * (1 - IFNULL(D.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (
            END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'
        )
  )
  AND (C.DAILY_FEE * 30 * (1 - IFNULL(D.DISCOUNT_RATE, 0) / 100)) >= 500000
  AND (C.DAILY_FEE * 30 * (1 - IFNULL(D.DISCOUNT_RATE, 0) / 100)) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;





# WITH FEES AS (
#     SELECT CASE WHEN END_DATE-START_DATE < 7 THEN DAILY_FEE*(END_DATE-START_DATE)
#            ELSE DAILY_FEE*(END_DATE-START_DATE)*(1-P.DISCOUNT_RATE/100)
#            END AS FEE
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#     RIGHT JOIN CAR_RENTAL_COMPANY_CAR C
#     ON (P.CAR_TYPE = C.CAR_TYPE AND  
#             )

# SELECT CAR_ID, CAR_TYPE, FEE
# FROM CAR_RENTAL_COMPANY_CAR C
#      JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
#      ON C.CAR_ID = H.CAR_ID
#      LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#      ON C.CAR_TYPE = P.CAR_TYPE

# WHERE C.CAR_TYPE IN ('세단', 'SUV') AND
#       (START_DATE > '2022-11-30' AND END_DATE > '2022-11-30') OR
#       (START_DATE < '2022-11-01' AND END_DATE < '2022-11-01')
# ORDER BY FEE DESC, CAR_ID DESC ;



