-- 코드를 입력하세요
SELECT V.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS I INNER JOIN REST_REVIEW AS V ON I.REST_ID = V.REST_ID
WHERE SUBSTR(ADDRESS, 1, 2) = '서울'
GROUP BY V.REST_ID
ORDER BY 6 DESC, 4 DESC;

# SELECT * FROM REST_REVIEW ;