SELECT V.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS I INNER JOIN REST_REVIEW AS V ON I.REST_ID = V.REST_ID
WHERE SUBSTR(ADDRESS, 1, 2) = '서울'
GROUP BY V.REST_ID
--  생각나는 대로 코드를 쓰다가 ORDER BY를 먼저 쓰고 GROUP BY를 쓰는 것을 잊어버려 헤맸다
--  SELECT 문에 집계함수가 들어가면 반드시 GROUP BY를 바로 짝지어 준다
ORDER BY 6 DESC, 4 DESC;



# SELECT * FROM REST_REVIEW ;
