# 2025-08-01 자력 해결
# 푸는 데 15분 넘게 걸렸는데 구매 건수를 세는 것이 아니라 구매한 유저 수를 세는 것이었다..

WITH CLEAR_USERS AS (
    SELECT *
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM CLEAR_USERS AS C
JOIN ONLINE_SALE AS O
ON C.USER_ID = O.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1, 2, 3 ;
       
