# 2025-08-03 14:15 못 푼 문제
# WITH에 지나치게 의존하다 서브쿼리 생각을 못한 케이스

WITH USER_2021 AS (

    SELECT USER_ID
    FROM USER_INFO
     WHERE YEAR(JOINED) = 2021
 ),
 PURCHASED_USERS AS (
     SELECT DISTINCT YEAR(SALES_DATE) AS YEAR,
            MONTH(SALES_DATE) AS MONTH,
            USER_ID
     FROM ONLINE_SALE
     WHERE USER_ID IN (SELECT USER_ID FROM USERS_2021)
 )

 SELECT 
     P.YEAR, 
     P.MONTH,
     COUNT(P.USER_ID) AS PURCHASED_USERS,
     ROUND(COUNT(P.USER_ID) / (SELECT COUNT(*) FROM USERS_2021), 1) AS PURCHASED_RATIO
 FROM PURCHASED_USERS P
 GROUP BY P.YEAR, P.MONTH
 ORDER BY P.YEAR, P.MONTH;


# WITH FILTER AS (
#     SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
#            U.USER_ID, PRODUCT_ID
#     FROM USER_INFO U LEFT JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
#     WHERE YEAR(JOINED) = 2021
#                 )
# SELECT YEAR, MONTH, COUNT(DISTINCT USER_ID), COUNT(PRODUCT_ID) / COUNT(DISTINCT USER_ID)
# FROM FILTER
# GROUP BY YEAR, MONTH

# 
    
# WITH JOINED_2021_SALES_TABLE AS (
#     SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.USER_ID
#     FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
#     WHERE YEAR(U.JOINED) = 2021
# ),
# JOINED_2021 AS (
#     SELECT 
#         CASE WHEN YEAR(O.SALES_DATE) IS NOT NULL THEN YEAR(O.SALES_DATE)
#         ELSE 'N' END AS YEAR,
#         CASE WHEN MONTH(O.SALES_DATE) IS NOT NULL THEN MONTH(O.SALES_DATE)
#         ELSE 'N' END AS MONTH,
#         UI.USER_ID
#     FROM USER_INFO UI LEFT JOIN ONLINE_SALE O ON UI.USER_ID = O.USER_ID
#     WHERE YEAR(UI.JOINED) = 2021
# )
   
# SELECT YEAR, MONTH, ROUND(COUNT(USER_ID) / 75, 1) AS PUCHASED_RATIO
# FROM JOINED_2021
# WHERE YEAR != 'N'
# GROUP BY YEAR, MONTH


WITH T1 AS (
    SELECT
        COUNT(DISTINCT USER_ID) AS PUCHASED_USERS
    FROM ONLINE_SALE
    WHERE USER_ID IN (
        SELECT USER_ID
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
    )
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
),
T2 AS (
    SELECT
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS
    FROM ONLINE_SALE AS OS
    INNER JOIN USER_INFO AS UI
    ON OS.USER_ID = UI.USER_ID
    WHERE YEAR(UI.JOINED) = 2021
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
),
T3 AS (
    SELECT
        COUNT(USER_ID) AS TOTAL_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT
    T2.YEAR,
    T2.MONTH,
    T2.PUCHASED_USERS,
    ROUND(T2.PUCHASED_USERS / T3.TOTAL_USERS, 1) AS PUCHASED_RATIO
FROM T2, T3
ORDER BY T2.YEAR, T2.MONTH;
