WITH RECURSIVE ECOLI_HIERARCHY AS (
    -- 1. 최초 개체(1세대) 설정
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 2. 부모를 따라가며 세대 증가
    SELECT e.ID, e.PARENT_ID, h.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN ECOLI_HIERARCHY h ON e.PARENT_ID = h.ID
)

-- 3. 각 세대별로 자식이 없는 개체 개수 세기
SELECT COUNT(h.ID) AS COUNT, h.GENERATION
FROM ECOLI_HIERARCHY h
LEFT JOIN ECOLI_DATA e ON h.ID = e.PARENT_ID
WHERE e.PARENT_ID IS NULL  -- 자식이 없는 개체만 선택
GROUP BY h.GENERATION
ORDER BY h.GENERATION;

