# SELECT H.HISTORY_ID,
#        CASE WHEN END_DATE - START_DATE < 7
#             THEN DAILY_FEE * (END_DATE - START_DATE)
#             WHEN END_DATE - START_DATE < 30
#             THEN DAILY_FEE * (END_DATE - START_DATE) * (SELECT 1-DISCOUNT_RATE/100)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
#      INNER JOIN CAR_RENTAL_COMPANY_CAR AS C
#      ON H.CAR_ID = C.CAR_ID
#      INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
#      ON C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_TYPE = '트럭'
# # ORDER BY FEE DESC, HISTORY_ID DESC;

# SELECT 
#     DISTINCT H.HISTORY_ID,
#     CASE 
#         WHEN (H.END_DATE - H.START_DATE + 1) >= 90 THEN ROUND(C.DAILY_FEE * (H.END_DATE - H.START_DATE + 1) * (1 - D.DISCOUNT_RATE/100), 0)
#         WHEN (H.END_DATE - H.START_DATE + 1) >= 30 THEN ROUND(C.DAILY_FEE * (H.END_DATE - H.START_DATE + 1) * (1 - D.DISCOUNT_RATE/100), 0)
#         WHEN (H.END_DATE - H.START_DATE + 1) >= 7 THEN ROUND(C.DAILY_FEE * (H.END_DATE - H.START_DATE + 1) * (1 - D.DISCOUNT_RATE/100), 0)
#         ELSE ROUND(C.DAILY_FEE * (H.END_DATE - H.START_DATE + 1), 0)
#         END AS FEE
# FROM 
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# JOIN 
#     CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
# LEFT JOIN 
#     CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE 
#     AND (
#         ((H.END_DATE - H.START_DATE + 1) >= 90 AND D.DURATION_TYPE = '90일 이상')
#         OR ((H.END_DATE - H.START_DATE + 1) >= 30 AND D.DURATION_TYPE = '30일 이상')
#         OR ((H.END_DATE - H.START_DATE + 1) >= 7 AND D.DURATION_TYPE = '7일 이상')
#     )
# WHERE 
#     C.CAR_TYPE = '트럭'
# ORDER BY 

#     FEE DESC, H.HISTORY_ID DESC;





# WITH DISCOUNT_TABLE AS 


SELECT 
    H.HISTORY_ID,
    ROUND(
        (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100) * C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) +1), 0
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON P.CAR_TYPE = C.CAR_TYPE
    AND (
        (DATEDIFF(H.END_DATE, H.START_DATE) >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE) < 30 AND P.DURATION_TYPE = '7일 이상')
        OR (DATEDIFF(H.END_DATE, H.START_DATE) >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) < 90 AND P.DURATION_TYPE = '30일 이상')
        OR (DATEDIFF(H.END_DATE, H.START_DATE) >= 90 AND P.DURATION_TYPE = '90일 이상')
    )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;

