WITH FILTER AS (
    SELECT APNT_NO, PT_NO, D.MCDP_CD, DR_NAME,
           APNT_YMD
    FROM APPOINTMENT A JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
    WHERE APNT_CNCL_YN = 'N' AND D.MCDP_CD = 'CS'
        AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
)

SELECT F.APNT_NO, P.PT_NAME, F.PT_NO, F.MCDP_CD, F.DR_NAME, F.APNT_YMD 
FROM FILTER F JOIN PATIENT P ON F.PT_NO = P.PT_NO
ORDER BY APNT_YMD ;

# SELECT APNT_NO, PT_NO, MCDP_CD, APNT_YMD
# FROM APPOINTMENT A
# WHERE APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
# AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
# AND A.MCDP_CD IN (SELECT D.MCDP_CD FROM DOCTOR D)


