# WITH CODES AS (
#     SELECT CODE
#     FROM SKILLCODES
#     WHERE CATEGORY = 'Front End')

# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS D, CODES
# WHERE D.SKILL_CODE & CODES.CODE > 0
# ORDER BY ID ;

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (SELECT * FROM SKILLCODES S
              WHERE S.CATEGORY = 'Front End'
              AND (d.SKILL_CODE & s.CODE) = s.CODE)
ORDER BY D.ID;

