-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN (SELECT T.ITEM_ID
                 FROM ITEM_TREE T
                 JOIN ITEM_INFO I
                 ON T.PARENT_ITEM_ID = I.ITEM_ID
                 WHERE I.RARITY = 'RARE')
ORDER BY ITEM_ID DESC;





# SELECT I.ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO AS I LEFT JOIN ITEM_TREE AS T ON I.ITEM_ID = T.PARENT_ITEM_ID
# WHERE I.RARITY = 'RARE'
# ORDER BY I.ITEM_ID DESC ;