-- 코드를 작성해주세요
# SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA AS A INNER JOIN ECOLI_DATA AS B
# ON A.ID = B.PARENT_ID
# ORDER BY A.ID ;

# SELECT E.ID, E.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA AS E INNER JOIN ECOLI_DATA AS P ON E.PARENT_ID = P.ID
# WHERE BITAND(E.GENOTYPE, P.GENOTYPE) = P.GENOTYPE
# ORDER BY E.ID;

# SELECT EC.ID, EC.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA EC
# JOIN ECOLI_DATA P ON EC.PARENT_ID = P.ID
# WHERE 
#     MOD(P.GENOTYPE, 2) <= MOD(EC.GENOTYPE, 2)
#     AND MOD(P.GENOTYPE / 2, 2) <= MOD(EC.GENOTYPE / 2, 2) 
#     AND MOD(P.GENOTYPE / 4, 2) <= MOD(EC.GENOTYPE / 4, 2)
#     AND MOD(P.GENOTYPE / 8, 2) <= MOD(EC.GENOTYPE / 8, 2) 
# ORDER BY EC.ID;

# SELECT child.ID, child.GENOTYPE, parent.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA child JOIN ECOLI_DATA parent ON child.PARENT_ID = parent.ID
# WHERE (child.GENOTYPE & parent.GENOTYPE) = parent.GENOTYPE
# ORDER BY child.ID;







SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C JOIN ECOLI_DATA AS P
WHERE C.PARENT_ID = P.ID AND
(C.GENOTYPE & P.GENOTYPE = P.GENOTYPE)
ORDER BY C.ID








