# 2025-07-26 15:15 내 의견 90% GPT 10%
# WITH문과 JOIN의 조합을 어제 배워서 바로 써먹으려 한 시도가 좋았음
# WITH x JOIN으로 필터를 걸었어도 필요하면 필터를 또 걸어야 한다는 것을 망각하고 답이 안 나온다고 좌절..
WITH FILTER AS (
    SELECT CAR_ID, COUNT(HISTORY_ID) AS COUNTS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)
SELECT MONTH(C.START_DATE) AS MONTH,
       C.CAR_ID,
       COUNT(C.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
     INNER JOIN FILTER AS F
     ON C.CAR_ID = F.CAR_ID
WHERE C.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
HAVING COUNT(C.HISTORY_ID) > 0
ORDER BY MONTH ASC, C.CAR_ID DESC ;


# 최초 시도 - 실패한 코드(집계함수의 값을 조건으로 쓰는 것은 단일 쿼리문으로는 불가능)
# SELECT MONTH(START_DATE) AS MONTH,
#        CAR_ID,
#        COUNT(HISTORY_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY MONTH(START_DATE), CAR_ID
# HAVING COUNT(HISTORY_ID) >= 5
# ORDER BY MONTH, CAR_ID DESC ;


