-- 코드를 입력하세요
# SELECT MONTH(START_DATE) AS MONTH,
#        CAR_ID,
#        COUNT(HISTORY_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY MONTH(START_DATE), CAR_ID
# HAVING COUNT(HISTORY_ID) >= 5
# ORDER BY MONTH, CAR_ID DESC ;

WITH FILTER AS (
    SELECT CAR_ID, COUNT(HISTORY_ID) AS COUNTS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)
SELECT MONTH(C.START_DATE) AS MONTH,
       C.CAR_ID,
       COUNT(C.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
     INNER JOIN FILTER AS F
     ON C.CAR_ID = F.CAR_ID
WHERE C.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
HAVING COUNT(C.HISTORY_ID) > 0
ORDER BY MONTH ASC, C.CAR_ID DESC ;
