# SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM DEVELOPERS D
# WHERE (D.SKILL_CODE & 256) > 0 
#     OR (D.SKILL_CODE & 1024) > 0
#      OR (D.SKILL_CODE & 1280) > 0 
# ORDER BY D.ID;

SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d
WHERE d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN ('Python', 'C#')) > 0
ORDER BY d.ID;
