# 2025-07-23 17:40 못 푼 문제
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       (MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)))
       - SIZE_OF_COLONY AS YEAR_DEV,
       ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV

# 행 수가 줄어들지 않는 것에서 GROUP BY를 쓰지 않는다는 것은 알았으나 대체할 방법을 찾지 못함
# 윈도우 함수의 존재를 잊어버린 것이 패착
# 



# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
#        MAX(SIZE_OF_COLONY) - SIZE_OF_COLONY AS YEAR_DEV,
#        ID
# FROM ECOLI_DATA 
# ORDER BY YEAR, YEAR_DEV







