# SELECT ID, N.FISH_NAME, LENGTH
# FROM FISH_INFO I JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
# WHERE LENGTH IN
# (SELECT MAX(LENGTH) FROM FISH_INFO GROUP BY I.FISH_TYPE)
# ORDER BY ID ;

WITH RankedFishes AS (
    SELECT
        F.ID,
        F.FISH_TYPE,
        F.LENGTH,
        N.FISH_NAME,
        RANK() OVER (PARTITION BY F.FISH_TYPE ORDER BY F.LENGTH DESC, F.ID ASC) AS RANKING
    FROM
        FISH_INFO F
    JOIN
        FISH_NAME_INFO N
    ON
        F.FISH_TYPE = N.FISH_TYPE
)
SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM
    RankedFishes
WHERE
    RANKING = 1
ORDER BY
    ID ASC;
