# 2025-07-25 17:10 못 푼 문제
# 한 번도 직접 써 본 적이 없는 3중 조인을 해야만 풀리는 문제
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
# JOIN을 2번 하면 3개 집합의 교집합 부분만 범위로 선택됨
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
ORDER BY I.ID;


# WITH MAX_SIZES AS (
#     SELECT I.FISH_TYPE, MAX(LENGTH) AS MAX_SIZE
#     FROM FISH_INFO I
#     WHERE LENGTH IS NOT NULL
#     GROUP BY I.FISH_TYPE
# )

# SELECT DISTINCT ID, FISH_NAME, LENGTH
# FROM FISH_INFO I 
# JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
# JOIN MAX_SIZES M ON I.LENGTH = M.MAX_SIZE
# ORDER BY ID ;


# SELECT ID, FISH_NAME, LENGTH
# FROM FISH_INFO AS I JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
# WHERE LENGTH IN
#               (SELECT FISH_TYPE, MAX(LENGTH)
#               FROM FISH_INFO
#               GROUP BY FISH_TYPE)
# ORDER BY ID






# SELECT I.ID, N.FISH_NAME, MAX(LENGTH)
# FROM FISH_INFO I JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
# GROUP BY I.FISH_TYPE
# ORDER BY I.ID ;

