# SELECT
# CASE WHEN
# (D.SKILL_CODE & 16 > 0) OR (D.SKILL_CODE & 2048 > 0) OR (D.SKILL_CODE & 8192 > 0)
# AND D.SKILL_CODE & 256 > 0
# THEN 'A'

# CASE WHEN D.SKILL_CODE & 1024 > 0
# THEN 'B'

# CASE ELSE 'C' END AS GRADE, ID, EMAIL
# FROM DEVELOPERS

WITH FRONTEND_CODE AS (
    SELECT SUM(CODE) AS CODE 
    FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
),
PYTHON_CODE AS (
    SELECT CODE 
    FROM SKILLCODES 
    WHERE NAME = 'Python'
),
CSHARP_CODE AS (
    SELECT CODE 
    FROM SKILLCODES 
    WHERE NAME = 'C#'
)
SELECT 
    CASE 
        WHEN d.SKILL_CODE & f.CODE > 0 AND d.SKILL_CODE & p.CODE > 0 THEN 'A'
        WHEN d.SKILL_CODE & c.CODE > 0 THEN 'B'
        WHEN d.SKILL_CODE & f.CODE > 0 THEN 'C'
    END AS GRADE,
    d.ID,
    d.EMAIL
FROM DEVELOPERS d
JOIN FRONTEND_CODE f ON 1=1
JOIN PYTHON_CODE p ON 1=1
JOIN CSHARP_CODE c ON 1=1
WHERE 
    (d.SKILL_CODE & f.CODE > 0 AND d.SKILL_CODE & p.CODE > 0)
    OR (d.SKILL_CODE & c.CODE > 0)
    OR (d.SKILL_CODE & f.CODE > 0)
ORDER BY GRADE, d.ID ;
